### ISSUE TITLE
1.c.ii

### ISSUE THREAD

**Issue by willidu** [uio-fys-mek/md-prosjekt#1]
Mulighet for å få en presisering eller omformulering av oppgaven? Hva menes med characteristic time scale? Hvilken størrelsesorden er rimelig å få som svar?

**Comment by willidu** [comment]
@Myrvixen @evenmn

**Comment by anjohan** [comment]
Hei, @willidu 

I 1ci) må du definere den karakteristiske tiden tau for å få likning (3) på riktig form. tau er uttrykt ved sigma, epsilon og m. Disse er materialspesifikke konstanter, og i 1cii) får du verdien deres for argon.

For å sjekke at du har fått riktig svar, anbefaler jeg å se på enhetene. Har uttrykket ditt for tau riktig enhet? Tau skal være en tid.

**Comment by evenmn** [comment]
Jeg hadde glemt å skru på varslinger, beklager det (de er på nå). Takk for at du tok deg tid til å svare, @anjohan (neste gang du er i Oslo må du komme innom CCSE!). @willidu du kan forvente at den karakteristiske tiden er i størrelsesorden picosekunder.
