### ISSUE TITLE
Velocity Verlet

### ISSUE THREAD

**Issue by willidu** [uio-fys-mek/md-prosjekt#2]
Jeg ser det står 'you should avoid having to
calculate the acceleration more than once per timestep' i Appendix for velocity verlet metoden. Hvordan implementeres dette? Løkka mi ser slik ut enn så lenge:
`    for i in range(n-1):
        a_ = a(x[i], t[i])
        x[i+1] = x[i] + v[i]*dt + 0.5*a_*dt**2
        a_2 = a(x[i+1], t[i+1])
        v[i+1] = v[i] + 0.5*(a_ + a_2)*dt`

**Comment by evenmn** [comment]
Det man må gjennomskue, er at akselerasjonen a_2 vil være den samme som a_ på neste tidssteg. Med andre ord vil koden ovenfor regne ut alle akselerasjoner to ganger. Siden beregninger av akselerasjon er flaskehalsen i koden deres, burde man unngå dette. 

En måte å gjøre det på, er å regne ut den initielle akselerasjonen utenfor løkken, og erstatte den gamle akselerasjonen med den nye på slutten av løkka,

```
a_ = a(x[0], t[0])
for i in range(n-1):
    x[i+1] = ...
    a_2 = a(x[i+1], t[i+1])
    v[i+1] = ...
    a_ = a_2
```

Det er også mulig å regne ut hastigheten i to steg, noe som gjør at man ikke trenger to akselerasjonsvariabler:

```
a_ = a(x[0], t[0])
for i in range(n-1):
    v[i+1] = v[i] + 0.5 * a_ * dt
    x[i+1] = x[i] + v[i+1] * dt
    a_ = a(x[i+1], t[i+1])
    v[i+1] = v[i+1] + 0.5 * a_ * dt
```

Sistnevnte krever noen flere flyttallsoperasjoner, men er kanskje mer ryddig og intuitiv
